pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  steps:
  - script: |
      # Set a pipeline variable using ##vso[task.setvariable]
      echo "##vso[task.setvariable variable=MyPipelineVariable]TheValueYouWantToSet"
      
      # Use the variable in the same job but a different step
      echo "The value of MyPipelineVariable is $MyPipelineVariable"
    displayName: 'Set and Use Variable in Step 1'

  - script: |
      # Use the variable in another step within the same job
      echo "Using MyPipelineVariable in Step 2: $MyPipelineVariable"
    displayName: 'Use Variable in Step 2'